server:
  port: 9099
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1587391396/springcloudbusdemo
          username:
          password:
          search-paths: springcloudbusdemo/springcloud-web/src/main/resources
  rabbitmq:
    host: 192.168.43.129
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8088/eureka
